sudo: required
services:
  - docker

before_install:
  - docker build -t dragonslayer142/docker-react -f DockerfileDev .

script:
  - docker run dragonslayer142/docker-react npm run test -- --coverage
